source 'https://rubygems.org'


gem 'rails', '4.2.9'
gem 'sass-rails', '~> 5.0'

# gem 'jquery-rails'


# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]


gem 'webpacker'
