source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '5.1.4'
gem 'sass-rails', '5.0.6'
gem 'webpacker'
gem 'uglifier'
gem 'js-routes'
gem 'roar', '1.0.1'
gem 'rack-throttle', '~> 0.4.2'
gem 'representable', '2.1.7'
gem 'versionist'
gem 'dynamic_form'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'rake'

gem 'oauth2_provider', '1.0.3', path: 'vendor/engines/oauth2_provider'
gem 'validatable', '>=1.6.0'

group :development, :test do
  gem 'rspec-rails'
  gem 'capybara'
  gem 'listen'
  gem 'jasmine-rails'

  gem 'rspec_junit_formatter'
  gem 'rails-controller-testing'

  # to enable debugging, turn on debug flag:
  # -Djruby.debug.fullTrace=true
  # gem 'pry'
  # git 'https://github.com/ketan/pry-debugger-jruby' do
  #   gem 'pry-debugger-jruby'
  # end
  # gem 'pry-state'
end
